name: guapswap-ergo-node

services:
  node:
    container_name: ergo-node
    image: ergoplatform/ergo:${ERGO_NODE_VERSION:-latest}
    command: --${ERGO_NODE_NETWORK_TYPE} -c /etc/ergo.conf
    volumes:
      - ./ergo_node:/home/ergo/.ergo
      - ./ergo_node/ergo.conf:/etc/ergo.conf:ro
    ports:
      - ${ERGO_NODE_PORT}:${ERGO_NODE_PORT}
      - ${ERGO_NODE_API_PORT}:${ERGO_NODE_API_PORT}
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xms${ERGO_NODE_HEAP_SIZE:-4G} -Xmx${ERGO_NODE_HEAP_SIZE:-4G}
    env_file:
      - .env
    logging:
      options:
        max-size: 50m
        max-file: 1

networks:
  default:
    external: false
    name: ergo-node-network
